import { AISemanticNodeKind } from "@/features/ai/types";

export const SEMANTIC_NODE_KINDS: AISemanticNodeKind[] = [
  "service",
  "database",
  "server",
  "api",
  "queue",
  "cache",
  "storage",
  "cdn",
  "dns",
  "firewall",
  "waf",
  "load-balancer",
  "internet",
  "kubernetes",
  "pod",
  "cluster",
  "container",
  "worker",
  "service-mesh",
  "deployment",
  "namespace",
  "region",
  "availability-zone",
  "vm",
  "user",
  "mobile",
  "browser",
  "lambda",
  "event-bus",
  "secrets",
  "authentication",
  "gateway",
  "message-broker",
  "ai-model",
  "agent",
  "tool",
  "memory",
  "knowledge-base",
  "vector-store",
  "dashboard",
  "alerting",
  "config",
  "cicd",
  "workflow",
  "decision",
  "parallel",
  "retry",
  "loop",
  "external",
  "generic",
];

export const readShapeRegistry = () => ({
  nativeShapes: [
    "rectangle",
    "circle",
    "diamond",
    "triangle",
    "line",
    "arrow",
    "arrow-bidirectional",
    "text",
    "semantic-node",
  ],
  semanticKinds: SEMANTIC_NODE_KINDS,
});
