/**
 * core/graph/graph-metadata.ts
 *
 * GraphMetadataRegistry — bridges the layout engine's CanvasElement output
 * back to the logical AgentGraph.
 *
 * Problem: when Groq first ran, the route.ts layout engine emitted
 * CanvasElement[] (shapes with pixel coords). The AI agent needs the logical
 * AgentGraph to reason about the diagram. CanvasElement alone loses metadata
 * like layer, column, and shape type for architecture diagrams.
 *
 * Solution:
 * 1. The route.ts mapper stamps each node CanvasElement with a
 *    `logicalId` field (non-rendered, added in buildNodeAndArrowElements).
 * 2. When the AI modal calls /api/generate-diagram with mode=update, it sends
 *    back the CanvasElement[] array including those stamps.
 * 3. GraphMetadataRegistry.reconstruct() reads the stamps and rebuilds the
 *    full AgentGraph, including fields (layer, column, shape) that the pure
 *    canvas element doesn't carry.
 *
 * This registry is ephemeral — created per request, never stored globally.
 */

import type { AgentNode, NodeShape } from "@/core/ai/types";
import { GraphStore } from "@/core/graph/graph-store";

// The shape of elements that the route.ts layout engine emits.
// We reference only the fields we need; the rest are ignored.
export interface ReconstructableElement {
  id: string;
  type: string;
  label?: string;
  /** Logical node id stamped by the layout mapper */
  logicalId?: string;
  /** Stamped logical shape */
  logicalShape?: NodeShape;
  /** Stamped layer (architecture) */
  logicalLayer?: string;
  /** Stamped column hint (architecture) */
  logicalColumn?: number;
  /** For edges: connection info */
  startConnection?: { elementId: string; anchorId: string };
  endConnection?: { elementId: string; anchorId: string };
  /** Agent-set fill — stamped by mapNodeToElement for round-trip persistence */
  logicalFill?: string;
  /** Agent-set text color — stamped by mapNodeToElement for round-trip persistence */
  logicalColor?: string;
}

export class GraphMetadataRegistry {
  /**
   * Stores logical metadata keyed by canvasElementId.
   * Map<canvasElementId, AgentNode>
   */
  private readonly byCanvasId = new Map<string, AgentNode>();

  /**
   * Call this when the layout engine produces a canvas element for a node.
   * This should be called from route.ts during the mapping phase.
   */
  register(canvasElementId: string, node: AgentNode): void {
    this.byCanvasId.set(canvasElementId, node);
  }

  /**
   * Reconstructs an AgentGraph from CanvasElement[] received from the client.
   *
   * For elements that were generated by this server (have logicalId stamps),
   * we directly reconstruct from the stamp fields.
   *
   * For elements without stamps (manually drawn by the user), we infer the
   * logical attributes from what's available on the canvas element itself.
   */
  reconstruct(elements: ReconstructableElement[]): GraphStore {
    let store = GraphStore.empty();

    // Phase 1: Reconstruct nodes
    for (const el of elements) {
      const isArrow = el.type === "arrow" || el.type === "arrow-bidirectional";

      if (isArrow) continue;

      // For guide elements (layer labels, cluster labels) — skip
      if (!el.label && !el.logicalId) continue;

      // If we have the logical stamp, use it directly
      const logicalId = el.logicalId ?? el.id;
      const label = el.label ?? logicalId;
      const shape = inferShape(el);
      const layer = inferLayer(el);
      const column = el.logicalColumn;

      const node: AgentNode = {
        id: logicalId,
        label,
        shape,
        ...(layer !== undefined ? { layer } : {}),
        ...(column !== undefined ? { column } : {}),
        ...(el.logicalFill ? { fill: el.logicalFill } : {}),
        ...(el.logicalColor ? { color: el.logicalColor } : {}),
      };

      const result = store.createNode(node);
      if (result instanceof Error) {
        // Skip duplicates (can happen with guide overlaps) — not fatal
        continue;
      }
      store = result;
      // Map canvas id → logical id for edge reconstruction
      this.byCanvasId.set(el.id, node);
    }

    // Phase 2: Reconstruct edges from arrow elements
    for (const el of elements) {
      if (el.type !== "arrow" && el.type !== "arrow-bidirectional") continue;
      if (!el.startConnection || !el.endConnection) continue;

      const fromNode = this.byCanvasId.get(el.startConnection.elementId);
      const toNode = this.byCanvasId.get(el.endConnection.elementId);
      if (!fromNode || !toNode) continue;

      const result = store.createEdge(fromNode.id, toNode.id, {
        bidirectional: el.type === "arrow-bidirectional",
        dashed: false,
      });
      if (result instanceof Error) {
        // Duplicate or invalid — skip silently, not fatal
        continue;
      }
      store = result.store;
    }

    return store;
  }
}

// ─── Inference helpers ───────────────────────────────────────────────────────

function inferShape(el: ReconstructableElement): NodeShape {
  if (el.logicalShape) return el.logicalShape;
  if (el.type === "circle") return "circle";
  if (el.type === "diamond") return "diamond";
  return "rectangle";
}

function inferLayer(
  el: ReconstructableElement,
): AgentNode["layer"] | undefined {
  if (el.logicalLayer) {
    const validLayers = ["edge", "application", "data", "observability"];
    if (validLayers.includes(el.logicalLayer)) {
      return el.logicalLayer as AgentNode["layer"];
    }
  }
  return undefined;
}

// ─── Singleton helper (scoped per request, NOT global) ───────────────────────

/**
 * Creates a fresh GraphMetadataRegistry for use within a single request.
 * Never share registries across requests.
 */
export function createMetadataRegistry(): GraphMetadataRegistry {
  return new GraphMetadataRegistry();
}
